//
//  domainNames.h
//  iso8583_ParseUtil
//
//  Created by Chen Defore on 2017/3/16.
//  Copyright © 2017年 Chen Defore. All rights reserved.
//

#ifndef domainNames_h
#define domainNames_h

/* 000 */#define MSG_TYPE_INDICATOR @"MSG_TYPE_INDICATOR"
/* 001 */#define BITMAP_EXTEND @"BITMAP_EXTEND"
/* 002 */#define PRIMARY_ACCOUNT_NUM @"PRIMARY_ACCOUNT_NUM"
/* 003 */#define PROCESS_CODE @"PROCESS_CODE"
/* 004 */#define TRANSACTION_AMOUNT @"TRANSACTION_AMOUNT"
/* 005 */#define SETTLEMENT_AMOUNT @"SETTLEMENT_AMOUNT"
/* 006 */#define CARDHOLDER_AMOUNT @"CARDHOLDER_AMOUNT"
/* 007 */#define DATE_AND_TIME_TRANSMISSION @"DATE_AND_TIME_TRANSMISSION"
/* 008 */#define Cardholder_billing_fee_Amount @"Cardholder_billing_fee_Amount"
/* 009 */#define CONVERSION_RATE_RECONCILIATION @"CONVERSION_RATE_RECONCILIATION"
/* 010 */#define CONVERSION_RATE_CARDHOLDER_BILLING @"CONVERSION_RATE_CARDHOLDER_BILLING"
/* 011 */#define SYSTEMS_TRACE_AUDIT_NUMBER @"SYSTEMS_TRACE_AUDIT_NUMBER"
/* 012 */#define DATE_AND_TIME_LOCAL_TRANSACTION @"DATE_AND_TIME_LOCAL_TRANSACTION"
/* 013 */#define DATE_EFFECTIVE @"DATE_EFFECTIVE"
/* 014 */#define DATE_EXPIRATION @"DATE_EXPIRATION"
/* 015 */#define DATE_SETTLEMENT @"DATE_SETTLEMENT"
/* 016 */#define DATE_CONVERSION @"DATE_CONVERSION"
/* 017 */#define DATE_CAPTURE @"DATE_CAPTURE"
/* 018 */#define MERCHANT_TYPE @"MERCHANT_TYPE"
/* 019 */#define COUNTRY_CODE_ACQUIRING_INSTITUTION @"COUNTRY_CODE_ACQUIRING_INSTITUTION"
/* 020 */#define COUNTRY_CODE_PRIMARY_ACCOUNT_NUMBER @"COUNTRY_CODE_PRIMARY_ACCOUNT_NUMBER"
/* 021 */#define COUNTRY_CODE_FORWARDING_INSTITUTION @"COUNTRY_CODE_FORWARDING_INSTITUTION"
/* 022 */#define POINT_OF_SERVICE_DATA_CODE @"POINT_OF_SERVICE_DATA_CODE"
/* 023 */#define CARD_SEQUENCE_NUMBE @"CARD_SEQUENCE_NUMBE"
/* 024 */#define NETWORK_INTERNATIONAL_ID @"NETWORK_INTERNATIONAL_ID"
/* 025 */#define POINT_OF_SERVICE_CONDITION_CODE @"POINT_OF_SERVICE_CONDITION_CODE"
/* 026 */#define POINT_OF_SERVICE_PIN_CAPTURE_CODE @"POINT_OF_SERVICE_PIN_CAPTURE_CODE"
/* 027 */#define AUTHORIZATION_IDENTIFICATION_RESP_LEN @"AUTHORIZATION_IDENTIFICATION_RESP_LEN"
/* 028 */#define AMOUNT_TRANSACTION_FEE @"AMOUNT_TRANSACTION_FEE"
/* 029 */#define AMOUNT_SETTLEMENT_FEE @"AMOUNT_SETTLEMENT_FEE"
/* 030 */#define AMOUNT_TRANSACTION_PROCESSING_FEE @"AMOUNT_TRANSACTION_PROCESSING_FEE"
/* 031 */#define AMOUNT_SETTLEMENT_PROCESSING_FEE @"AMOUNT_SETTLEMENT_PROCESSING_FEE"
/* 032 */#define ACQUIRER_INSTITUTION_IDENT_CODE @"ACQUIRER_INSTITUTION_IDENT_CODE"
/* 033 */#define FORWARDING_INSTITUTION_IDENT_CODE @"FORWARDING_INSTITUTION_IDENT_CODE"
/* 034 */#define PAN_EXTENDED @"PAN_EXTENDED"
/* 035 */#define TRACK_2_DATA @"TRACK_2_DATA"
/* 036 */#define TRACK_3_DATA @"TRACK_3_DATA"
/* 037 */#define RETRIEVAL_REFERENCE_NUM @"RETRIEVAL_REFERENCE_NUM"
/* 038 */#define APPROVAL_CODE @"APPROVAL_CODE"
/* 039 */#define RESPONSE_CODE @"RESPONSE_CODE"
/* 040 */#define SERVICE_RESTRICTION_CODE @"SERVICE_RESTRICTION_CODE"
/* 041 */#define CARD_ACCEPTOR_TERMI_IDENTIFICATION @"CARD_ACCEPTOR_TERMI_IDENTIFICATION"
/* 042 */#define CARD_ACCEPTOR_IDENTIFICATION_CODE @"CARD_ACCEPTOR_IDENTIFICATION_CODE"
/* 043 */#define CARD_ACCEPTOR_NAME_LOCATION @"CARD_ACCEPTOR_NAME_LOCATION"
/* 044 */#define ADDITIONAL_RESPONSE_DATA @"ADDITIONAL_RESPONSE_DATA"
/* 045 */#define TRACK_1_DATA @"TRACK_1_DATA"
/* 046 */#define ADITIONAL_DATA_ISO @"ADITIONAL_DATA_ISO"
/* 047 */#define ADITIONAL_DATA_NATIONAL @"ADITIONAL_DATA_NATIONAL"
/* 048 */#define ADITIONAL_DATA_PRIVATE @"ADITIONAL_DATA_PRIVATE"
/* 049 */#define CURRENCY_CODE_TRANSACTION @"CURRENCY_CODE_TRANSACTION"
/* 050 */#define CURRENCY_CODE_SETTLEMENT @"CURRENCY_CODE_SETTLEMENT"
/* 051 */#define CURRENCY_CODE_CARDHOLDER_BILLING @"CURRENCY_CODE_CARDHOLDER_BILLING"
/* 052 */#define PERSONAL_PIN_DATA @"PERSONAL_PIN_DATA"
/* 053 */#define SECUR_RELATED_CTRL_INFO @"SECUR_RELATED_CTRL_INFO"
/* 054 */#define AMOUNTS_ADDITIONAL @"AMOUNTS_ADDITIONAL"
/* 055 */#define RESERVED_ISO_0 @"RESERVED_ISO_0"
/* 056 */#define RESERVED_ISO_1 @"RESERVED_ISO_1"
/* 057 */#define RESERVED_NATIONAL_0 @"RESERVED_NATIONAL_0"
/* 058 */#define RESERVED_NATIONAL_1 @"RESERVED_NATIONAL_1"
/* 059 */#define RESERVED_NATIONAL_2 @"RESERVED_NATIONAL_2"
/* 060 */#define RESERVED_PRIVATE_0 @"RESERVED_PRIVATE_0"
// TODO
/* 061 */#define RESERVED_PRIVATE_1 @"RESERVED_PRIVATE_1"
/* 062 */#define RESERVED_PRIVATE_2 @"RESERVED_PRIVATE_2"
/* 063 */#define RESERVED_PRIVATE_3 @"RESERVED_PRIVATE_3"
/* 064 */#define MSG_AUTHENTICATION_CODE_FIELD @"MSG_AUTHENTICATION_CODE_FIELD"


///* 065 */ IFB_BINARY(8, "BITMAP, EXTENDED"),
///* 066 */ IF_CHAR(1, "SETTLEMENT CODE"),
///* 067 */ Extended payment data", true),
///* 068 */ Country code, receiving institution",
///* 069 */ Country code, settlement institution",
///* 070 */ Country code, authorizing agent Inst.", true),
///* 071 */  4, "Message number", true),
///* 072 */  4, "MESSAGE NUMBER LAST", true),
///* 073 */ IF_CHAR(6, "DATE ACTION"),
///* 074 */  10, "Credits, number", true),
///* 075 */  10, "Credits, reversal number", true),
///* 076 */  10, "Debits, number", true),
///* 077 */  10, "Debits, reversal number", true),
///* 078 */  10, "Transfer, number", true),
///* 079 */  10, "Transfer, reversal number", true),
///* 080 */  10, "Inquiries, number", true),
///* 082 */ IFB_LLNUM(12, "CREDITS, PROCESSING FEE AMOUNT", true),
///* 083 */ IFB_LLNUM(12, "CREDITS, TRANSACTION FEE AMOUNT", true),
///* 084 */ IFB_LLNUM(12, "DEBITS, PROCESSING FEE AMOUNT", true),
///* 085 */ IFB_LLNUM(12, "DEBITS, TRANSACTION FEE AMOUNT", true),
//
///* 086 */ IFB_LLNUM(16, "Credits, amount", true),
///* 087 */ IFB_LLNUM(16, "Credits, reversal amount", true),
///* 088 */ IFB_LLNUM(16, "Debits, amount", true),
///* 089 */ IFB_LLNUM(16, "Debits, reversal amount", true),
//
///* 090 */ ORIGINAL_DATA_ELEMENTS,
///* 091 */ FILE UPDATE_CODE,
///* 092 */ FILE SECURITY_CODE,
///* 093 */ RESPONSE INDICATOR,
///* 094 */ SERVICE INDICATOR,
///* 095 */ REPLACEMENT AMOUNTS,
///* 096 */ MSG_SECURITY_CODE,
//
///* 097 */ AMOUNT_NET_RECONCILIATION,
///* 098 */ PAYEE,
///* 099 */ SETTLEMENT_INSTITUTION_ID_CODE,
///* 100 */ RECEIVING_INSTITUTION_ID_CODE,
///* 101 */ FILE_NAME,
///* 102 */ ACCOUNT_IDENTIFICATION_1,
///* 103 */ ACCOUNT_IDENTIFICATION_2,
///* 104 */ TRANSACT_ON_ESCRIPTION,
///* 105 */ RESERVED_FOR_ISO_USE,
///* 106 */ RESERVED_FOR_ISO_USE,
///* 107 */ RESERVED_FOR_ISO_USE,
///* 108 */ RESERVED_FOR_ISO_USE,
///* 109 */ RESERVED_FOR_ISO_USE,
///* 110 */ RESERVED_FOR_NATIONAL_USE,
///* 111 */ RESERVED_FOR_NATIONAL_USE,
///* 112 */ RESERVED_FOR_NATIONAL_USE,
///* 113 */ RESERVED_FOR_NATIONAL_USE,
///* 114 */ RESERVED_FOR_NATIONAL_USE,
///* 115 */ RESERVED_FOR_NATIONAL_USE,
///* 116 */ RESERVED_FOR_NATIONAL_USE,
///* 117 */ RESERVED_FOR_PRIVATE_USE,
///* 118 */ RESERVED_FOR_PRIVATE_USE,
///* 119 */ RESERVED_FOR_PRIVATE_USE,
///* 120 */ RESERVED_FOR_PRIVATE_USE,
///* 121 */ RESERVED_FOR_PRIVATE_USE,
///* 122 */ RESERVED_FOR_PRIVATE_USE,
///* 123 */ RESERVED_FOR_PRIVATE_USE,
///* 124 */ RESERVED_FOR_PRIVATE_USE,
///* 125 */ RESERVED_FOR_PRIVATE_USE,
///* 126 */ RESERVED_FOR_PRIVATE_USE,
///* 127 */ RESERVED_FOR_PRIVATE_USE,
///* 128 */ MSG_AUTHENTICATION_CODE_FIELD,



#endif /* domainNames_h */
